### PR TITLE
Add relay field.

### PR DESCRIPTION
**Pull request by UmanShahzad**

### CODE REVIEW

**Review by HavenDV — APPROVED** [review]

**Comment by UmanShahzad** [comment]
@HavenDV We also now have a `service` field in the privacy object, which is a string but it is optional. Can you please help add that real quick?

**Comment by HavenDV** [comment]
> @HavenDV We also now have a `service` field in the privacy object, which is a string but it is optional. Can you please help add that real quick?

Sure. I want to point out that you can release releases by simply editing the [docs/openapi.yaml](https://github.com/ipinfo/csharp/edit/master/docs/openapi.yaml) file via github with the `feat:` or `fix:` commit prefix

**Comment by UmanShahzad** [comment]
@HavenDV That's very convenient!

**Comment by HavenDV** [comment]
Please check https://github.com/ipinfo/csharp/commit/e6f0278fc0afda527791b1f28a65f56df9fdcbaa

**Comment by UmanShahzad** [comment]
@HavenDV :+1: thank you!

**Pull request merged**
